version: "3"

services:
  nginx:
    image: nginx:1.23.3
    volumes:
      - ./nginx/nginx.conf:/Jenkins/nginx.conf:ro
      - ./nginx/cert.pem:/Jenkins/cert.pem
      - ./nginx/key.pem:/Jenkins/key.pem
    ports:
      - "80:80"
      - "443:443"

  certbot:
    ports:
      - "6000:80"
    env_file:
      - .env
    volumes:
      - ./nginx/:/Jenkins/
    build:
      context: ./certbot
      dockerfile: Dockerfile
      args:
        DOMAIN_EMAIL: ${DOMAIN_EMAIL}
        DOMAIN_URL: ${DOMAIN_URL}
