- name: my sample playbook
  hosts: [Azure]
  remote_user: nick
  become: true

  tasks:
  - name: Install DotNetCore
    snap:
      name: dotnet-sdk 
      channel: 3.1
      classic: yes
      state: present
